version: "3.7"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
    container_name: gostack_postgres
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: redis
